config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    resource :customer, only: [] do
      get 'my_page', to: 'customers#my_page', as: 'my_page'
      get 'information/edit', to: 'customers#information_edit', as: 'edit_information'
      patch 'information', to: 'customers#update', as: 'information'
      get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
      patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get 'search' => "searches#search"
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items,through: :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
  def customer_status
    is_active ? "有効" : "退会"
  end

  def active_for_authentication?
    super && is_active
  end
  
  def name
    "#{first_name} #{last_name}"
  end 
  
  def full_address
    "〒#{postal_code} #{address} #{name}"
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  # before_action :authenticate_admin!
  #  before_action :set_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "顧客情報を更新しました。"
      redirect_to admin_customer_path(@customer)
    else
      flash.now[:danger] = "顧客情報の更新に失敗しました。"
      render :edit
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
  def customer_restore
    @admin_customer = Customer.deleted.find(params[:id]).restore
    redirect_to admin_customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postcode, :phone_number, :is_deleted)
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
  
  def customer_restore
    @admin_customer = Customer.deleted.find(params[:id]).restore
    redirect_to admin_customers_path
  end

  def destroy
    @admins_customer = Customer.find(params[:id])
    @admins_customer.destroy
    redirect_to admin_customers_path
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.erb
<div class="container">
  <h1>会員情報編集</h1>
    <h3>会員ID  <%= @admins_customer.id %></h3>
      <%= form_for @admins_customer, :url => { :controller => :users, :action => :update } do |f| %>
        <% if @admins_customer.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h3><%= @admins_customer.errors.count %>error prohibited this obj from being saved:</h3>
            <ul>
              <% @admins_customer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <h3>氏名           <%= f.text_field :last_name %>  <%= f.text_field :first_name %></h3>
        <h3>フリガナ        <%= f.text_field :last_name %>  <%= f.text_field :first_name %></h3>
        <h3>郵便番号        <%= f.text_field :postal_code %></h3>
        <h3>住所            <%= f.text_field :user_address %></h3>
        <h3>電話番号        <%= f.number_field :telephone_number %></h3>
        <h3>メールアドレス   <%= f.text_field :email %></h3>
        <h3>会員ステータス
          <% if @admins_customer.deleted_at.nil? %>
            <%= link_to "退会", admins_customer_path, method: :delete, data:  { confirm: '本当に退会させますか？' }, class: "btn btn-danger" %>
          <% else %>
            <%= link_to "有効", user_restore_admins_customer_path(@admins_customer), method: :patch, class: "btn btn-primary" %>
          <% end %>
          <%= f.submit '変更を保存', class: "btn btn-primary" %>
        </h3>
      <% end %>
</div>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><p><span class="p-0.5 bg-secondary"><%= @customer.full_name %>さんの会員情報編集</span></p></h4>
      <table class="table table-borderless">
        <%= form_with model: [:admin, @customer] do |f| %>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %>　<%= f.text_field :first_name %></td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana %>　<%= f.text_field :first_name_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code %></td>
          <td></td>
        </tr>

        <tr>
          <td>住所</td>
          <td><%= f.text_field :address %></td>
          <td></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= f.number_field :telephone_number %></td>
          <td></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= f.email_field :email %></td>
          <td></td>
        </tr>
        
        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効", { value: :true }  %>
            
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会", { value: :false } %>
          </td>
        </tr>
        
        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/index.erb
<div class="container">
  <h1>会員一覧</h1>
     <table class="table">
        <thead>
          <tr>
            <th>顧客ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
            <% @admins_cutomers.each do |p| %>
             <tr>
              <td><%= p.id %></td>
              <td><%= link_to p.last_name, admins_customer_path(p.id)  %><%= link_to p.first_name, admins_customer_path(p.id)  %></td>
              <td><%= p.email  %></td>
                <% if p.deleted_at.nil? %>
                 <td>有効</td>
                <% else %>
                 <td>退会</td>
                <% end %>
             </tr>
            <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/customers/index.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col">
      <h4><p><span class="p-0.5 bg-secondary"> 会員一覧</span></p></h4>
        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.full_name, admin_customer_path(customer) %></td>
              <td><%= customer.email %></td>
              <td><%= customer.customer_status %></td>
            </tr>
          <% end %>
        </table>
    </div>
  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.erb
<div class="container">
  <h1><strong>会員詳細画面</strong></h1>


  <h3>顧客ID       <%= @admins_customer.id %><strong>

  </strong></h3>
  <h3>氏名       <%= @admins_customer.last_name %><%= @admins_customer.first_name %></h3>
  <h3>フリガナ    <%= @admins_customer.last_name_kana %><%= @admins_customer.first_name_kana %></h3>
  <h3>郵便番号       <%= @admins_customer.postal_code %></h3>
  <h3>住所        <%= @admins_customer.user_address %></h3>
  <h3>電話番号    <%= @admins_customer.tele_number %></h3>
  <h3>メールアドレス    <%= .email %></h3>
  
   <% if @admins_customer.deleted_at.nil? %>
      <td>有効</td>
    <% else %>
      <td>無効</td>
    <% end %>
    
  <%= link_to "編集する", edit_admins_customer_path(@admins_customer), data: {"turbolinks" => false}, class: "btn btn-primary" %>
  <%= link_to "注文履歴一覧を見る", admins_orders_path, data: {"turbolinks" => false}, class: "btn btn-primary" %>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><p><span class="p-0.5 bg-secondary"><%= @customer.full_name %>さんの会員詳細</span></p></h4>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
  
          <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
  
          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>
  
          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>
  
          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>
  
          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <th><%= @customer.customer_status %></th>
          </tr>

          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
            <%= link_to "注文履歴一覧を見る", "#", class:"btn btn-primary" %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>