config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    resource :customer, only: [] do
      get 'my_page', to: 'customers#my_page', as: 'my_page'
      get 'information/edit', to: 'customers#information_edit', as: 'edit_information'
      patch 'information', to: 'customers#update', as: 'information'
      get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
      patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get 'search' => "searches#search"
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
        "〒#{postal_code}#{address}#{name}"
    end     
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    validates :amount,presence:true
    def subtotal
      item.with_tax_price * amount
    end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items,through: :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
  def customer_status
    is_active ? "有効" : "退会"
  end

  def active_for_authentication?
    super && is_active
  end
  
  def name
    "#{first_name} #{last_name}"
  end 
  
  def full_address
    "〒#{postal_code} #{address} #{name}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :genre_id, presence: true
    validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
      
    has_one_attached :image
    
    def with_tax_price
        (price*1.1).floor
    end
    
    def self.looks(word)
      Item.where("name LIKE?","%#{word}%")
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details,dependent: :destroy
    belongs_to :customer
    attr_accessor :address_option
    has_one :ordered_item
    has_many :ordered_items

     has_one_attached :image
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status:{ payment_confirmation:0,production:1,preparation_for_shipping:2,sent:3}
    def full_address
     "〒#{postal_code}#{address}#{name}"
    end
    def with_tax_price
       (cart_item.price*1.1).floor
    end
    def subtotal
      items.with_tax_price*amount
    end
    def status_in_japanese
        I18n.t("enums.order.status.#{status}")
    end     
end 
   

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status: { cannot_start: 0, waiting_for_production: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price * amount
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  
    belongs_to :order
    belongs_to :item
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
#  before_action :authenticate_admin!
  
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  #before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.all
    # @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:error] = @item.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    # @item = Item.find(params[:id]) 不要: set_itemメソッドで設定されるため
  end

  def edit
    # @item = Item.find(params[:id]) 不要: set_itemメソッドで設定されるため
  end

  def update
    if @item.update(item_params)
      flash[:success] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品詳細の変更内容に不備があります。"
      render :edit
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :genre_id, :price, :is_active, :image, :introduction)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  # before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_orders_path, notice: 'ユーザ情報を更新しました。'
    else
      @customer = @order.customer
      @order_details = @order.order_details
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :total_payment, :created_at, :payment_method, :status, :shipping_cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def after_sign_in_path_for(resource)
  #     case resource
  #     when Admin
  #       admin_path
  #     when Customer
  #       root_path
  #     else
  #       root_path
  #     end
  # end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @word = params[:word]
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
 <div class='row'>
  <h4><p><span class="p-0.5 bg-secondary"> 注文履歴一覧</span></p></h4>
     <table class="table">
        <thead>
          <tr>
            <th>購入日時　</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>入金ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
           <tr>
             <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M"), admin_order_path(order.id), data: {"turbolinks" => false}  %></td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td><%= order.customer.email  %></td>
            <td><%= order.status_in_japanese  %></td>
           </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <%= paginate @orders %>
</div>

app/views/admin/orders/show.html.erb
<div class="container mt-4">
  <h4><p><span class="px-3 bg-secondary text-white">注文履歴詳細</span></p></h4>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>購入者</th>
        <td><%= @customer.full_name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>〒<%= @order.postal_code %> <%= @order.address %><br><%= @order.name %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= t("enums.order.payment_method.#{@order.payment_method}") %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
            <div class="form-inline">
              <%= f.select :status, Order.statuses.keys.map { |k| [t("enums.order.status.#{k}"), k] }, {}, class: "form-control mr-2" %>
              <%= f.submit '更新', class: "btn btn-success" %>
            </div>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <h5 class="mt-4"><span class="px-3 bg-secondary text-white">商品詳細</span></h5>

  <table class="table table-bordered mt-3">
    <thead class="thead-light">
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= number_to_currency(order_detail.price, unit: "¥", precision: 0) %></td>
          <td><%= order_detail.amount %></td>
          <td><%= number_to_currency(order_detail.price * order_detail.amount, unit: "¥", precision: 0) %></td>
          <td>
            <%= form_with model: order_detail, url: admin_order_order_detail_path(@order, order_detail), method: :patch, local: true do |f| %>
              <div class="form-inline">
                <%= f.select :production_status, OrderDetail.production_statuses.keys.map { |k| [t("enums.order_detail.production_status.#{k}"), k] }, {}, class: "form-control mr-2" %>
                <%= f.submit '更新', class: "btn btn-success" %>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row mt-4">
    <div class="col-6">
      <p><strong>商品合計</strong>: <%= number_to_currency(@order.order_details.sum { |detail| detail.price * detail.amount }, unit: "¥", precision: 0) %></p>
      <p><strong>送料</strong>: <%= number_to_currency(@order.shipping_cost, unit: "¥", precision: 0) %></p>
      <p><strong>請求金額合計</strong>: <%= number_to_currency(@order.total_payment, unit: "¥", precision: 0) %></p>
    </div>
  <%= paginate orders %>
</div> 

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>