config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    resource :customer, only: [] do
      get 'my_page', to: 'customers#my_page', as: 'my_page'
      get 'information/edit', to: 'customers#information_edit', as: 'edit_information'
      patch 'information', to: 'customers#update', as: 'information'
      get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
      patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get 'search' => "searches#search"
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
        "〒#{postal_code}#{address}#{name}"
    end     
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    validates :amount,presence:true
    def subtotal
      item.with_tax_price * amount
    end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items,through: :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
  def customer_status
    is_active ? "有効" : "退会"
  end

  def active_for_authentication?
    super && is_active
  end
  
  def name
    "#{first_name} #{last_name}"
  end 
  
  def full_address
    "〒#{postal_code} #{address} #{name}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :genre_id, presence: true
    validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
      
    has_one_attached :image
    
    def with_tax_price
        (price*1.1).floor
    end
    
    def self.looks(word)
      Item.where("name LIKE?","%#{word}%")
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details,dependent: :destroy
    belongs_to :customer
    attr_accessor :address_option
    has_one :ordered_item
    has_many :ordered_items

     has_one_attached :image
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status:{ payment_confirmation:0,production:1,preparation_for_shipping:2,sent:3}
    def full_address
     "〒#{postal_code}#{address}#{name}"
    end
    def with_tax_price
       (cart_item.price*1.1).floor
    end
    def subtotal
      items.with_tax_price*amount
    end
    def status_in_japanese
        I18n.t("enums.order.status.#{status}")
    end     
end 
   

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status: { cannot_start: 0, waiting_for_production: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price * amount
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  
    belongs_to :order
    belongs_to :item
  
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(update_genre_params)
    redirect_to admin_genres_path
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
  def update_genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
#  before_action :authenticate_admin!
  
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  #before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.all
    # @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:error] = @item.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    # @item = Item.find(params[:id]) 不要: set_itemメソッドで設定されるため
  end

  def edit
    # @item = Item.find(params[:id]) 不要: set_itemメソッドで設定されるため
  end

  def update
    if @item.update(item_params)
      flash[:success] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品詳細の変更内容に不備があります。"
      render :edit
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :genre_id, :price, :is_active, :image, :introduction)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def after_sign_in_path_for(resource)
  #     case resource
  #     when Admin
  #       admin_path
  #     when Customer
  #       root_path
  #     else
  #       root_path
  #     end
  # end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @word = params[:word]
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h5 class="col-4 text-center my-4">
      <span class="px-3" style="background-color: #dcdcdc;">ジャンル編集</span>
    </h5>
  </div>
  <div class="row">
    <div class="col-6 my-4 form-group">
      <%= form_with model: @genre, method: :patch, url: admin_genre_path(@genre.id) do |f| %>
        <div class="form-inline">
          <p class="mx-3 my-1">ジャンル名</p>
          <%= f.text_field :name, class: "form-control mx-4", size: 40 %>
          <%= f.submit '変更を保存', class:'btn btn-success ml-auto' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h5 class="col-4 text-center my-4">
      <span class="px-3" style="background-color: #dcdcdc;">ジャンル一覧・追加</span>
    </h5>
  </div>
  
  <div class="row">
    <div class="col-6 my-4 form-group">
      <%= form_with model: @genre, url:admin_genres_path do |f| %>
        <div class="form-inline">
          <p class="mx-3 my-1">ジャンル名</p>
          <%= f.text_field :name, class: "form-control mx-4", placeholder: "ジャンル名", size: 40 %>
          <%= f.submit '新規登録', class:'btn btn-success ml-auto' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-4">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col-8"><span class="ml-5">ジャンル</span></th>
            <th class="col-4"></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre), class:'btn btn-success' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h3>商品編集</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <%= form_with model: [:admin, @item], local: true, html: { multipart: true } do |f| %>
        <table class="table">
          <tr>
            <th><%= f.label :image, "商品画像" %></th>
            <td>
              <% if @item.image.attached? %>
                <%= image_tag @item.image, class: "img-thumbnail", size: "150x150" %>
              <% else %>
                <%= image_tag "no_image.jpeg", class: "img-thumbnail", size: "150x150" %>
              <% end %>
              <%= f.file_field :image %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :name, "商品名" %></th>
            <td><%= f.text_field :name, placeholder: "商品名" %></td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "商品説明" %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder: "ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <th><%= f.label :genre_id, "ジャンル" %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %></td>
          </tr>
          <tr>
            <th><%= f.label :price, "税抜価格" %></th>
            <td><%= f.text_field :price, placeholder: "1000" %>円</td>
          </tr>
          <tr>
            <th><%= f.label :is_active, "販売ステータス" %></th>
            <td>
              <%= f.radio_button :is_active, true, checked: @item.is_active %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false, checked: !@item.is_active %>
              <%= f.label :is_active, "販売中止" %>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="text-center">
              <%= f.submit "変更を保存", class: "btn btn-success" %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h3>商品一覧</h3>
    </div>
    <div class="col-sm-2 px-sm-0 text-right mb-2">
      <%= link_to new_admin_item_path, class: "btn btn--circle btn--circle-c btn--shadow" do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <table class="table text-center admin-items mb-5">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>税込価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td class="align-middle"><%= item.id %></td>
              <td class="align-middle">
                <%= link_to admin_item_path(item.id) do %>
                  <u><%= item.name %></u>
                <% end %>
              </td>
              <td class="align-middle"><%= number_to_currency(item.price, unit: "¥",precision:0) %></td>
              <td class="align-middle"><%= number_to_currency(item.with_tax_price, unit: "¥",precision:0) %></td>
              <td class="align-middle"><%= item.genre.name %></td>
              <td class="align-middle">
                <% if item.is_active %>
                  <p class="text-success font-weight-bold">販売中</p>
                <% else %>
                  <p class="text-danger font-weight-bold">販売停止中</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品新規登録</h2>
      <% if flash[:error].present? %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with(model: @item, url: admin_items_path, local: true) do |f| %>
      <table>
        <tr>
          <th><%= f.label :商品画像 %></th>
          <td><%= f.file_field :image,size:'100×100' %></td>
        </tr>
        <tr>
          <th><%= f.label :商品名 %></th>
          <td><%= f.text_field :name, placeholder: "商品名" %></td>
        </tr>
        <tr>
          <th><%= f.label :商品説明 %></th>
          <td><%= f.text_area :introduction, size: "50x5", placeholder: "ここに説明文を記述します" %></td>
        </tr>
        <tr>
          <th><%= f.label :ジャンル %></th>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %></td>
        </tr>
        <tr>
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder: "1000" %>円</td>
        </tr>
        <tr>
          <th><%= f.label :販売ステータス %></th>
          <td>
            <%= f.radio_button :is_active, true, checked: true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中" %>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="text-center">
            <%= f.submit "新規登録", class: "btn btn-success" %>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row text-center text-xs-center text-sm-left text-md-left">
    <div class="col-xs-12 col-sm-6 col-md-6 mx-auto text-right">
      <% if @item.image.attached? %>
        <%= image_tag @item.image.variant(resize: "200x200"), class: "lb" %>
      <% else %>
        <%= image_tag "no_image.jpeg", class: "lb", size: "200x200" %>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 item-details mx-auto">
      <h2><strong><%= @item.name %></strong></h2>
      <h4><%= simple_format(@item.introduction) %></h4>
      <% if @item.is_active %>
        <p class="text-success">販売中</p>
        <h3> <%= number_to_currency(@item.with_tax_price, unit: "¥",precision:0) %> (税込)</h3>
      <% else %>
        <h3 class="text-danger">販売停止中です</h3>
      <% end %>
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
    </div>
  </div>
</div>