config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    resources :items, only: [:index, :show]
    resource :customer, only: [] do
      get 'my_page', to: 'customers#my_page', as: 'my_page'
      get 'information/edit', to: 'customers#information_edit', as: 'edit_information'
      patch 'information', to: 'customers#update', as: 'information'
      get 'unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
      patch 'withdraw', to: 'customers#withdraw', as: 'withdraw'
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm', as: 'confirm'
        get 'thanks', to: 'orders#thanks', as: 'thanks'
      end
    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get 'search' => "searches#search"
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
        "〒#{postal_code}#{address}#{name}"
    end     
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    validates :amount,presence:true
    def subtotal
      item.with_tax_price * amount
    end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  has_many :items,through: :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
  def customer_status
    is_active ? "有効" : "退会"
  end

  def active_for_authentication?
    super && is_active
  end
  
  def name
    "#{first_name} #{last_name}"
  end 
  
  def full_address
    "〒#{postal_code} #{address} #{name}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :genre_id, presence: true
    validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
      
    has_one_attached :image
    
    def with_tax_price
        (price*1.1).floor
    end
    
    def self.looks(word)
      Item.where("name LIKE?","%#{word}%")
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details,dependent: :destroy
    belongs_to :customer
    attr_accessor :address_option
    has_one :ordered_item
    has_many :ordered_items

     has_one_attached :image
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status:{ payment_confirmation:0,production:1,preparation_for_shipping:2,sent:3}
    def full_address
     "〒#{postal_code}#{address}#{name}"
    end
    def with_tax_price
       (cart_item.price*1.1).floor
    end
    def subtotal
      items.with_tax_price*amount
    end
    def status_in_japanese
        I18n.t("enums.order.status.#{status}")
    end     
end 
   

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status: { cannot_start: 0, waiting_for_production: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price * amount
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  
    belongs_to :order
    belongs_to :item
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
#  before_action :authenticate_admin!
  
  def top
    @orders = Order.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def after_sign_in_path_for(resource)
  #     case resource
  #     when Admin
  #       admin_path
  #     when Customer
  #       root_path
  #     else
  #       root_path
  #     end
  # end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @word = params[:word]
    @items = Item.looks(params[:word])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<li class="nav-item mr-3">
    <%= link_to '商品一覧', dmin_items_path, class: 'nav-link btn btn-outline-secondary' %></li>
<li class="nav-item mr-3">
    <%= link_to '会員一覧', admin_customers_path, class: 'nav-link btn btn-outline-secondary' %></li>
<li class="nav-item mr-3">
    <%= link_to '注文履歴一覧', admin_orders_path, class: 'nav-link btn btn-outline-secondary' %></li>
<li class="nav-item">
    <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link btn btn-outline-secondary'%></li>
<li class="nav-item">
    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary'%></li>

app/views/layouts/_before_signin_header.html.erb
<li class="nav-item mr-3">
    <%= link_to 'about', about_path, class: 'nav-link btn btn-outline-secondary' %></li>
<li class="nav-item mr-3">
    <%= link_to '商品一覧', items_path, class: 'nav-link btn btn-outline-secondary' %></li>
<li class="nav-item mr-3">
    <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link btn btn-outline-secondary' %></li>
<li class="nav-item">
    <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link btn btn-outline-secondary'%></li>

app/views/layouts/_customer_header.html.erb
<li class="nav-item mr-3">
  <%= link_to 'マイページ', my_page_customer_path, class: 'nav-link btn btn-outline-secondary' %>
</li>
<li class="nav-item mr-3">
  <%= link_to '商品一覧', items_path, class: 'nav-link btn btn-outline-secondary' %>
</li>
<li class="nav-item mr-3">
  <%= link_to 'カート', cart_items_path, class: 'nav-link btn btn-outline-secondary' %>
</li>
<li class="nav-item">
  <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary' %>
</li>

app/views/layouts/_footer.html.erb
<footer class="container-fluid border-top align-items-center">
  <div class="row w-100 justify-content-center">
    <div class="col-4 text-center">
      <% flash.each do |key, message| %>
      　　<div class="alert alert-<%= key %> mb-2"><%= message %></div>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top border-bottom bg-white">
  <nav class="">
    <div class="container-fluid">
      <div class="row">
        <div class="col-3 pl-4">
          <a class="navbar-brand" href="/">Nagano Cake</a>
          <a class="navbar-brand" href="/"><%= image_tag('nagano_cake.jpg', size: "75x75") %></a>
        </div>
        <div class="col-3">
          <% if customer_signed_in? %>
            <p class="mt-4">ようこそ、<%= current_customer.last_name %>さん！</p>
          <% end %>
        </div>
        <div class="col-6">
          <div class="row justify-content-end mr-1">
            <ul class="nav">
              <% if admin_signed_in? %>
                <%= render 'layouts/admin_header' %>
              <% elsif customer_signed_in? %>
                <%= render 'layouts/customer_header' %>
              <% else %>
                <%= render 'layouts/before_signin_header' %>
              <% end %>
            </ul>
          </div>
          <div class="row justify-content-end mr-1 mt-1">
            <%= form_with url: search_path, method: :get do |f| %>
            <div class="input-group">
              <%= f.text_field :word, placeholder: "Search" %>
              <%= button_tag type: "submit", class: "btn btn-outline-primary btn-sm" do %>
                <i class="fa-solid fa-magnifying-glass"></i>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

<!--<form class="d-flex" role="search">-->
<!--  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--  <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--</form>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano_Cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<<<<<<< HEAD
    
    <script src="https://kit.fontawesome.com/ae44b1616f.js" crossorigin="anonymous"></script>
=======

    <script src="https://kit.fontawesome.com/96781c3f85.js" crossorigin="anonymous"></script>

>>>>>>> origin/takahaya
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <%= flash[:notice]%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>